const THREE = window["THREE"];
export const MeshStandardMaterial = THREE.MeshStandardMaterial;
export const BoxGeometry = THREE.BoxGeometry;
export const Mesh = THREE.Mesh;
export const Vector3 = THREE.Vector3;
export const Scene = THREE.Scene;
export const Color = THREE.Color;
export const PerspectiveCamera = THREE.PerspectiveCamera;
export const AmbientLight = THREE.AmbientLight;
